models:
  - name: "anthropic/claude-sonnet-4"
    provider: "openrouter"
    supports_images: true
  - name: "anthropic/claude-opus-4"
    provider: "openrouter"
    supports_images: true
  - name: "meta-llama/llama-3.1-8b-instruct"
    provider: "openrouter"
    supports_images: false
  - name: "openai/gpt-5-chat"
    provider: "openrouter"
    supports_images: true
  - name: "local"
    provider: "local"
    supports_images: false
  - name: "moonshotai/kimi-k2"
    provider: "openrouter"
    supports_images: false
  - name: "gemini-2.5-flash-preview-05-20"
    provider: "google"
    supports_images: true
  - name: "deepseek/deepseek-r1-0528"
    provider: "openrouter"
    supports_images: false
